image: golang:1.16

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

stages:
  - test
  - build
  - release

default:
  tags:
    - mintel

vet:
  stage: test
  script:
    - make lint

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make build
    - find build/ -type f | xargs gzip
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/*

release:
  stage: release
  image: python:3
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - pip install requests click
    - python scripts/release.py $CI_PROJECT_DIR/build/*
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/*

