image: golang:1.15-buster

stages:
  - vet
  - build
  - test
  - release

vet:
  stage: vet
  script:
    - go install golang.org/x/tools/cmd/goimports
    - make lint

test:
  stage: test
  script:
    - go test -v ./...

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/glmr

release:
  stage: release
  image: python:3
  only:
    - tags
  script:
    - pip install gitlab-release
    - gitlab-release $CI_PROJECT_DIR/glmr
  artifacts:
    paths:
      - $CI_PROJECT_DIR/glmr

