image: golang:1.15-buster

stages:
  - vet
  - build
  - test
  - release

before_script:
  - apt update
  - apt install -y libgit2-dev

vet:
  stage: vet
  script:
    - go install golang.org/x/tools/cmd/goimports
    - go vet ./...
    - test $(goimports -l . | wc -l) -eq 0

test:
  stage: test
  script:
    - go test -v ./...

build:
  stage: build
  script:
    - go build -o $CI_PROJECT_DIR ./...
  artifacts:
    paths:
      - $CI_PROJECT_DIR/glmr

release:
  stage: release
  image: python:3
  only:
    - tags
  script:
    - pip install gitlab-release
    - gitlab-release $CI_PROJECT_DIR/glmr
  artifacts:
    paths:
      - $CI_PROJECT_DIR/glmr

