image: golang:1.16

stages:
  - test
  - build
  - release

default:
  tags:
    - mintel

vet:
  stage: test
  script:
    - make lint

test:
  stage: test
  script:
    - make test

build:
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/*

release:
  stage: release
  image: python:3
  only:
    - tags
  script:
    - pip install requests click
    - python scripts/release.py $CI_PROJECT_DIR/build/*
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/*

